name: Deploy SSDT Database Custom

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Шаг 1: Скачиваем актуальный код из репозитория
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Шаг 2: Создаем алиас (ссылку) на MSBuild вручную, минуя vswhere
      - name: Setup Custom MSBuild Path
        run: |
          echo "C:\Program Files\Microsoft Visual Studio\18\Insiders\MSBuild\Current\Bin" >> $env:GITHUB_PATH

      # Шаг 3: Находим утилиту NuGet
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1

      # Шаг 4: Восстанавливаем зависимости решения перед сборкой
      - name: Restore NuGet packages
        run: nuget restore Nexus.slnx

      # Шаг 5: Компилируем базу данных и публикуем её
      - name: Build and Publish SSDT Project
        run: |
          msbuild /t:Build,Publish /p:SqlPublishProfilePath=Nexus.publish.xml /p:Configuration=Release
