name: Deployment Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action_type:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted

    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Environment check
        run: echo "Building for ${{ inputs.environment }}..."

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build SSDT Project (.sqlproj)
        run: |
          msbuild /t:Build /p:Configuration=Release Nexus.sqlproj

      - name: Publish dacpac structure to Remote Template DB
        shell: pwsh
        run: |
          SqlPackage `
            /Action:Publish `
            /SourceFile:"bin\Release\Nexus.dacpac" `
            /TargetServerName:"${{ vars.DB_SERVER }}" `
            /TargetDatabaseName:"${{ vars.DB_NAME }}" `
            /TargetTrustedConnection:True `
            /p:AllowDropBlockingDatabaseObjects=True `
            /p:BlockOnPossibleDataLoss=True `
            /p:DropObjectsNotInSource=False