name: CI/CD Pipeline

on:
  push:
    branches: [ new ] # Триггер на главную ветку
    tags: [ 'v*' ] # Или триггер на релизные теги (например, v1.0.0)

jobs:
  # Деплой на DEV происходит всегда при пуше в main
  deploy-dev:
    uses: ./.github/workflows/deployment-template.yml
    with:
      environment: qa
    secrets: inherit # Передает секреты в reusable workflow

  # Деплой на TEST запускается автоматически после успешного DEV
  # deploy-test:
    # needs: deploy-dev
    # uses: ./.github/workflows/deployment-template.yml
    # with:
      # environment: staging
    # secrets: inherit

  # Деплой на PROD запускается только при создании тега (релиза)
  # deploy-prod:
    # if: startsWith(github.ref, 'refs/tags/')
    # uses: ./.github/workflows/deployment-template.yml
    # with:
      # environment: production
    # secrets: inherit
