name: CI/CD Pipeline

on:
  push:
    branches: [ new ] # Триггер на главную ветку
    tags: [ 'v*' ] # Или триггер на релизные теги (например, v1.0.0)

jobs:
  build-template:
    #if: github.event_name == 'push' && github.ref_name == 'new'
    uses: ./.github/workflows/deployment-template.yaml
    with:
      environment: dev
      action_type: "build_template"
    secrets: inherit
  # deploy-dev on push in main
  deploy-dev:
    name: Local
    uses: ./.github/workflows/deployment-template.yaml
    with:
      environment: dev
      action_type: dev_deploy
    secrets: inherit # Передает секреты в reusable workflow

  # Деплой на TEST запускается автоматически после успешного DEV d
  deploy-test:
    needs: deploy-dev
    uses: ./.github/workflows/deployment-template.yaml
    with:
      environment: qa
      action_type: qa_deploy
    secrets: inherit

  # Деплой на PROD запускается только при создании тега (релиза)
  # deploy-prod:
    # if: startsWith(github.ref, 'refs/tags/')
    # uses: ./.github/workflows/deployment-template.yaml
    # with:
      # environment: production
    # secrets: inherit
